### PR TITLE
fix(CO-431): modify LDAP access to delegated admin

### PR DESCRIPTION
**Pull request by aheeva-yuliya**

### CODE REVIEW

**Review by keshavbhatt — APPROVED** [review]
These changes tested?

**Review by Polpetta — CHANGES_REQUESTED** [review]
LGTM but needs testing, please add some

**Review by frisonisland — CHANGES_REQUESTED** [review]
I will also ask for testing, I would start from unit testing (that may require breaking some things down but it's the way to go).
For Integration testing you can get some idea from what we did here (mocking the context): https://github.com/Zextras/carbonio-mailbox/pull/28/files#diff-647c00e30b7f0c114e5e8935e213816a2078e786e5287891796d316e49ae8289 
but I'm not sure the same mocking classes are available in this project.

**Comment by aheeva-yuliya** [comment]
carbonio-ldap-utils-store was removed from building and packaging process.

**Pull request closed without merging**
